### ISSUE TITLE
Typo in github action's message for creating issues and PRs.

### ISSUE THREAD

**Issue by maskedman0** [mayajs/maya#47]
## 📝 Describe the bug

I saw the `greetings.yml` file under .github >> workflow directory, is that a typo error?

**`greetings.yml` **
```yml

name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating your first issue. Keep collaborating!!!'' first issue'
        pr-message: 'Thank you for creating your first PR. We will review it shortly.'' first pr'

```
